package com.gogo.steelbotrun.vkbot.core.command

import com.gogo.steelbotrun.vkbot.core.command.Lexer.Companion.replaceNewLineTokens
import com.gogo.steelbotrun.vkbot.bot.event.MessageInfo
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.comparables.shouldBeEqualComparingTo
import io.kotest.matchers.ints.shouldBeExactly

class CommandsTests : StringSpec({
	"NewLine tokens should have delimiters generated by replaceNewLineTokens" {
		"a,b,c;abc".replaceNewLineTokens() shouldBeEqualComparingTo "a , b , c ; abc"
		" ;a, b".replaceNewLineTokens() shouldBeEqualComparingTo "  ; a ,  b"
	}
	"Lexer should return correct number of tokens" {
		Lexer.getTokens("").count() shouldBeExactly 0
		Lexer.getTokens("Token").count() shouldBeExactly 1
		Lexer.getTokens("  Token    SomeOtherToken").count() shouldBeExactly 2
		Lexer.getTokens(" Token   Token2  Token3    ").count() shouldBeExactly 3
	}
	"Parser should return correct number of commands" {
		val messageInfo = MessageInfo("1", 1, 1, 1)

		val message = Message(messageInfo, "Function Argument1")
		message.commands.count() shouldBeExactly 1

		val message2 = Message(messageInfo, "Function Argument1, Function2 Argument2")
		message2.commands.count() shouldBeExactly 2

		val message3 = Message(messageInfo, "Function Argument1;Function2 Argument2")
		message3.commands.count() shouldBeExactly 2
	}
})
